### ISSUE TITLE
Slide off-center in Safari

### ISSUE THREAD

**Issue by rachgo** [bigcartel-themes/picklejuice#127]
In Safari, letting slideshow play through to the end, last slide shows up over to the left. Resizing the browser window seems to snap it back in place.

http://lavenderbluebaby.bigcartel.com

![screen shot 2015-01-19 at 3 04 56 pm](https://cloud.githubusercontent.com/assets/3578349/5807893/237d3f70-9fed-11e4-8aa6-5ef99ad8256e.png)

**Comment by fennen529** [comment]
I looked at the shop before it seemed like they added the images incorrectly. There should always be full screen and they were not before which was probable causing the error. Since I have returned to the shop they now have full screen images so they must have re-uploaded them and this seems to have fixed their issue.
